### ISSUE TITLE
Basic functions for constructing a google map

### ISSUE THREAD

**Issue by jeffdyer** [artcompiler/L207#1]
Functions:
-- map: construct a map (pick reasonable defaults)
-- location: [{string | coordinates}] - array of string or coordinates to locate on map 
-- zoom: number - map zoom scale
-- height: number - map height (default to height of window)
-- width: number - map width (default to width of window)

e.g. 'location "Boulder, CO" scale ... height 450 width 600 map'

**Comment by jeffdyer** [comment]
Here is a version that supports 'map', 'center' and 'zoom'.

   http://www.graffiticode.com/item?id=78372+38905

We still need to add 'location' to drop pins at different locations and width and height to size the panel. If location is specified and center is not, then the location should determine the center of the map. If more then one location is specified then the point between the locations should determine the center of the map. If zoom is not specified, then the locations should determine the zoom by some "smart" algorithm to be determined.

**Comment by wbaldwin6** [comment]
All functions have been added with full functionality.
