### ISSUE TITLE
Default 'zoom'

### ISSUE THREAD

**Issue by jeffdyer** [artcompiler/L207#4]
If 'zoom' is not specified, be smart about its default. Use the following as a guide for 'center' and 'location' with one position:

1: World
5: Landmass/continent
10: City
15: Streets
20: Buildings

For 'location' with two positions, use some multiple (e.g. 2x) of the difference of the longitudes or latitudes, which ever is greater.

**Comment by wbaldwin6** [comment]
Used fitbounds to base the map zoom and center on the bounds of the markers by default.
